  
language: node_js
addons:
  apt:
    chrome: stable
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
- '6'
before_install:
- npm install -g @angular/cli
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install: npm install
branches:
  only:
  - master
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
